# Generated by Django 3.1.4 on 2020-12-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201212_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('profile', models.FileField(upload_to='files')),
            ],
        ),
    ]
