# Generated by Django 3.1.4 on 2020-12-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201212_0208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='some photo', upload_to='images/'),
        ),
    ]
